### PR TITLE
Nrichers/sc 2887/release notes script updates

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This PR reimplements our release notes script from scratch.

What's better about this script:

- **Specify any number of release tag URLs**. The old script could handle only one release tag per repo but our pattern over the past year has been that we often combine multiple release tags into a single set of release notes. This meant running the old script several times and manually collating the files. 
- **Generate release notes as a single file**. When we created our original release notes script, we separated the different label categories into multiple output files. We don't generate that much content, though, and manually collated those releases notes into a single file. We now generate a single file from the start. 
- **Requires much less editing**. Better markup, with H3 headings for all entries instead of the previous list items is much easier to work with and requires far fewer manual tweaks to look right. For example, additional markup inside of the release notes such as additional list items now typically just work as-is. Bonus: the "On this page" right side navigation now lists the entries in each section. 
- **Better at handling exceptions**. The old script was missing quite a bit of error handling. For example, it had not been able to correctly embed the release notes into _quarto.yml for some time due to changes to navigation in the docs site, but it never returned any errors. 

Other assorted improvements include a default publishing date three business days from running the script,  doing away with templates file, and moving the script into a new scripts/ path. 

### How to test

1. `gh pr checkout 177`
2. `cd site`
3. `make release-notes`

After generating the release notes, run `quarto preview` to see the new release notes.

### Output 

New release notes output files:

image

Release notes embedded into _quarto.yml:

image

### CODE REVIEW

**Comment by validbeck** [comment]
I just tried this out, but it looks like I have to first make a release note in GitHub — can I pull in the external release note from PR #176 to add, or is there another process?

**Comment by nrichers** [comment]
> I just tried this out, but it looks like I have to first make a release note in GitHub — can I pull in the external release note from PR https://github.com/validmind/documentation/pull/176 to add, or is there another process?

You just need to feed it any number of existing full release URLs, e.g. 

- https://github.com/validmind/documentation/releases/tag/v2.0.7
- https://github.com/validmind/frontend/releases/tag/v1.19.0
- https://github.com/validmind/developer-framework/releases/tag/v2.0.7

**Comment by validbeck** [comment]
> EDIT: And also try stuff that doesn't actually exist to test the error handling. 😁

Yep, I initially tried to plunk in my PR #176 and it didn't generate anything in the `release-notes.qmd` file. I tried the releases you suggested and it did compile them into a draft file! I assume we then clean these up and change it into a "Highlights" file?

- How would I include the release notes from the PR I made above?

**Comment by nrichers** [comment]
>  I assume we then clean these up and change it into a "Highlights"

No, that file name is a leftover from the days when we generated a slew of different files for the different labels (highlights, bug fixes, etc.) and then manually combined them into one. The file should just be called `release-notes.qmd` to reflect what's in it. (The date is provided by the URL.)

**Comment by nrichers** [comment]
> How would I include the release notes from the PR I made above?

You'd need to create a new release tag that includes the PR. Instructions forthcoming in the process I'm writing down for us.

**Comment by nrichers** [comment]
BTW, your questions about release tags make me think that the new, recent default of NOT playing animated GIFs in GitHub is a problem. The animated GIF basically shows what kind of release URLs you can enter. 🙃

**Comment by validbeck** [comment]
> BTW, your questions about release tags make me think that the new, recent default of NOT playing animated GIFs in GitHub is a problem. The animated GIF basically shows what kind of release URLs you can enter. 🙃

Yes, I figured it out after I watched the GIF, the first attempt was just a mistake on my part!

**Review by validbeck — APPROVED** [review]
It works as described — now to update our release notes!

**Comment by validbeck** [comment]
Ah, looks like the script is conflicting with our new `About` section where we moved the overview, contribute, releases & fineprint into guide — how do we resolve that? 🤔

**Comment by nrichers** [comment]
> Ah, looks like the script is conflicting with our new `About` section where we moved the overview, contribute, releases & fineprint into guide — how do we resolve that? 🤔

I fixed the merge conflict and retested to make sure the script still works. Previously, this would have broken the script, but as long as the embed marker for updating _quarto.yml is in the right place, the script will work.

**Pull request merged**
