### PR TITLE
Use Quarto profiles for rendering the site on GitHub and locally

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This PR enables our GitHub workflows and local Makefile to use Quarto profiles with Heap tracking for:

- Development (PR previews)
- Staging
- Production

Quarto profiles enable us to remove environment-specific rendering instructions out of GitHub branches which is a prerequisite to simplifying our merge strategy. 

Tracking for these profiles matches our [environments on Heap](https://heapanalytics.com/app/env/2282992095/manage/projects/2282992095):

| Environment | ID |
|--------|-------|
| Development | 3544910167 |
| Staging     | 3193732798 |
| Production  | 2282992095 |

### Development environment

`quarto preview --profile development`

image

### Staging environment

`quarto preview --profile staging`

image

### Production environment

`quarto preview --profile production`

image

### No tracking 

`quarto preview`

image

### CODE REVIEW

**Review by validbeck — APPROVED** [review]
Looks good! Only q is, is the `development` profile linked to the PR previews in `docs-demo`?

**Comment by nrichers** [comment]
> Looks good! Only q is, is the `development` profile linked to the PR previews in `docs-demo`?

Yes, we render the site for PR previews with `--profile development`. See https://github.com/validmind/documentation/pull/372/files#diff-97e4422bf78b64c199ffc642cb458be76ad2bd30b54a40c85846cfc7f2d35cebR35 for the details.

**Comment by nrichers** [comment]
> Looks good! Only q is, is the `development` profile linked to the PR previews in `docs-demo`?

Oh, there's an even better way to show you! Since this PR has a preview, we can verify in there that the right profile is being used:

image


`3544910167` maps to our development environment, so this is correct.

**Comment by nrichers** [comment]
Staging site deployed and also shows the correct Heap tracking — `3193732798`: 

image

**Pull request merged**
