### PR TITLE
Review and restructure articles for Onboarding section

### PR DESCRIPTION
**Pull request by noosheenv**
## Internal Notes for Reviewers
I tested the steps for `Manage groups` and `Manage users` against the UI, and made changes accordingly. Also, some of the formatting wasn't following the style guide, so I made edits there.

### Manage users:

| Before | After | 
| ----- | ------ |
| image| image |
| image | image |

### Manage groups:
| Before | After | 
| ----- | ----- |
| image | image |
| image | image |

I moved two sections (User groups & Add or remove group members) from `Manage users` to `Manage groups`. User groups had the same information as another section in `Manage groups`, so I consolodated the articles.

| Before | After |
| ----- | ----- |
| image | image |
|  image | image |

I'm testing making `View your profile` its own page. I would like to add a screenshot that doesn't leak my email but still looks professional.

| Before | After | 
| ----- | ------ |
| image | image |

Lastly, I changed the wording from `Onboarding` to `Setup`. These articles have sections that are accessed for onboarding, and sections for setup and maintenance. By switching to `Setup`, it still embodies `Onboarding`, but also includes use cases for configuring stuff after onboarding.

| Before | After |
| ----- | ----- |
| image | image |

### CODE REVIEW

**Comment by noosheenv** [comment]
I just pushed the changes we talked about yesterday! I am ready for review.

**Comment by noosheenv** [comment]
> * OR you forgot to include `user-setup.qmd` in your push

You're right, I did not push the `_quarto.yml` file somehow! Doing that now. That should also reflect the changes to the wording for `SETUP`... I was wondering why it wasn't showing in your screenshot! 
image

I swept for the margin convention, and there's no links to begin with, so yay! Just the log in to platform UI which is all good.

Thanks for the review, let me know if you can see the changes now!

**Comment by validbeck** [comment]
Whoo, I see the files now!

## Section
> I do think I prefer `CONFIGURATION` in the section, as viewing your profile isn't really setup but it IS configuration and it wraps the other things in neatly. 

## View your profile
- I would move this page to UNDER "Onboarding users" 
- **This CTA needs a little human-editing love,** too. ;)
- I would break down 2. into two separate steps, like you see in some of the other guides. Anytime there's a click, a step generally, unless it's wrapped into the same sub-menu. 
- **There are some actions you can take on this page.** You should explain how to do them instead of just stating that they exist. Remember that when you C&P sections from the docs, it's your responsibility to check them for accuracy and completeness instead of just moving them.
- You can further flesh out this page with a "What's next"... think about what might go well here!

> I swept for the margin convention, and there's no links to begin with, so yay! 

Yep, I'm telling you that there are some places you should add some, based on how they were added in other places. ;)

**Comment by noosheenv** [comment]
I did some meditation and edited the CTA. I feel like it has more life in it now:
"Managing your profile is essential for personalizing your user experience and ensuring you have access to the necessary tools and information. View your profile details, manage your onboarding preferences, enable dark mode, and access your API keys." 
The latest 2 commits should address your last comment :D

**Review by validbeck — APPROVED** [review]
> I did some meditation and edited the CTA. I feel like it has more life in it now

Nice! This is much better. 

## View your profile
- You're still just directing users to a page, instead of explaining the context of what they can do and how to do it. I've made the changes and pushed them, so all you need to do is pull them down and review them, but **please re-render the site and test the static files and upload them before merging this request.**
- For this one, you're not really referring to the right onboarding, so the margin link isn't relevant.
- I adjusted the "What's next" links too, as the ones you had before were a bit too specific.
> For the future, really think about **granular** actions from the perspective of someone who has never used the interface before, and make sure you stress-test the functionality you're writing about to catch any edge-cases too (like the restart option!).

| View your profile updates | Onboarding wizard |
|---|---|
| Screenshot 2024-06-27 at 11 47 36 AM | Screenshot 2024-06-27 at 11 38 40 AM |

## Set up your organization
- You missed some margin links on this page! No biggie, but it is part of this section.
Screenshot 2024-06-27 at 11 48 47 AM

**Pull request merged**
