### PR TITLE
Pulling in latest changes from PR184

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> Pulling in latest changes from https://github.com/validmind/developer-framework/pull/184 as an example for our internal Community processes. 

### Retrieve latest from `developer-framework`
Process doc here: https://www.notion.so/validmind/Retrieve-latest-from-developer-framework-c44be5deaf954b99b643b17797b59d89?pvs=4

### CODE REVIEW

**Review by nrichers — COMMENTED** [review]
This PR itself LGTM but I think there is an issue with the Python docs that needs to be fixed.

@cachafla it looks like the Python docs also pull in the test descriptions but they are missing the new tests for ongoing monitoring: 

image

You can look at this issue live in the PR preview by comparing:

- https://docs-demo.vm.validmind.ai/pr_previews/get-source/developer/model-testing/test-descriptions.html
- https://docs-demo.vm.validmind.ai/pr_previews/get-source/validmind/validmind/tests.html

**Comment by validbeck** [comment]
> it looks like the Python docs also pull in the test descriptions but they are missing the new tests for ongoing monitoring: 

I'll made a related Story!

**Comment by validbeck** [comment]
@nrichers @cachafla: https://app.shortcut.com/validmind/story/6491/missing-submodules-in-api-reference

**Review by nrichers — APPROVED** [review]
LGTM since the issue with the Python docs is unrelated to this PR. 📦

**Pull request merged**
