### PR TITLE
Invstigating test descriptions — DO NOT MERGE

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This PR includes the changes from @noosheenv's branch with generated test descriptions. This PR is mainly to figure out what happens when `make test-descriptions` gets run on a Windows environment. 

DO NOT MERGE.

@noosheenv @validbeck

### CODE REVIEW

**Comment by nrichers** [comment]
I grabbed the .md output files and fed them into ChatGPT: https://chat.openai.com/share/667ff6f5-6bc6-48f4-954b-414a7a20b2b6

The relevant piece in that conversation: 

Several files in the 'prompt_validation' folder are not encoded in UTF-8, which might be causing the build failures. Here's the encoding for each file:

- NegativeInstruction.md - ASCII
- Robustness.md - Windows-1252
- Delimitation.md - ASCII
- Conciseness.md - Windows-1252
- Bias.md - ASCII
- Clarity.md - Windows-1252
- Specificity.md - ASCII

The build process might be expecting files in UTF-8 encoding, and files in ASCII or Windows-1252 could lead to issues, especially if there are special characters.

**Comment by validbeck** [comment]
> The build process might be expecting files in UTF-8 encoding, and files in ASCII or Windows-1252 could lead to issues, especially if there are special characters.

Thanks Nik, this is helpful info — I was gonna ask ChatGPT to do the same this morning! I have a workaround that I will walk Noosheen thru until she gets the borrowed Mac from Andres.

**Comment by nrichers** [comment]
> I have a workaround that I will walk Noosheen thru until she gets the borrowed Mac from Andres.

@validbeck Noosheen won't be running `make get-source` very often (and certainly not for another sprint or two). Would you be OK with just putting this effort on pause for now?

**Comment by nrichers** [comment]
> She actually needs it for [sc-4382](https://app.shortcut.com/validmind/story/4382).

Can you run `make get-source` for her and push that to a new branch she can pull down for the subsequent steps? Spending time troubleshooting Windows is a sunk cost at this point.

**Comment by nrichers** [comment]
This PR was mainly to investigate issues on Windows. We're sidestepping those by having Noosheen work on macOS, closing.

**Pull request closed without merging**
