### PR TITLE
How-to video production discussion

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This is a working PR to sort out production issues with our videos, specifically around:

- **Video quality issues in Streamyard** and, to a lesser, extent audio quality issues
- **Length, structure, and placement** for our how-to videos to agree on internal guidelines

**[LIVE preview of the videos](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-4906/validation-experience-tech-deep-dive-videos/guide/guides.html#videos-to-be-discussed)**

### Streamyard

Local recordings were used for the best quality: 

image

Video recording was set to the highest 1080p setting, with "Touch up my appearance" turned off to avoid halo artefacts and general fuzziness: 

image

### Logitune app

The following additional settings to brightness and sharpness were used to improve the video appearance for the standard Logitech C920 I used:

image

## Video quality 

Video quality for participants is poor, even at the highest 1080p setting and with additional adjustments made via the webcam app. The video feed is grainy and blotchy, with halo artefacts:

image

Video quality for content borders on impossible to read:

image

Here's a detail close-up for better comparison:

| Streamyard | Local |
|--------|-------|
| image | image |

Overall, the video quality for Streamyard borders on **unusable**. 

**Next steps:**

- Try out Loom and Zoom as alternatives and compare quality differences (Loom has an affordable [Business tier](https://www.loom.com/pricing) that would allow us to remove their branding)
- Re-record these videos on a different platform when time permits

## Audio quality

Audio quality is OK-ish as long as I hover right next to the webcam microphone. But doing so makes using a talking head overlay impossible — no one wants a shot up your nose while you talk close to he microphone. 

**Next steps:**

- I would need to upgrade to a better standalone microphone for videos if you also want a talking head other than for short intros

### Length

The total length of all the videos is **10 minutes and 20 seconds** which is too long for a simple instructional video that gets embedded in a page. 

I ended up recording the validator experience video in _segments_ to make retakes easier and to create shorter video snippets that can be watched sequentially or embedded in different places: 

image

As an alternative to creating a single large video, you can [create a playlist](https://www.youtube.com/playlist?list=PL8vB59eD-pJ6srM3cuaxaqdC6jXRXhcBh) on YouTube that ties together all the videos and embed them via: 

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL8vB59eD-pJ6srM3cuaxaqdC6jXRXhcBh" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
```

image

### Structure

This section is here mostly as a precursor to future interal guidelines we can add to our style guide. It's incomplete.

#### End-to-end videos

The videos in this PR follow the validator training quite verbatim. This format works well to make sure you cover the essentials on what I would call an end-to-end video, or a 'super task' that itself contains several other smaller tasks, in this case:

- Reviewing model documentation
- Preparing a validation report
- Submitting it for approval after checking the workflow

#### Individual task how-tos

For shorter videos on individual tasks, we should run through the steps described on the page where the video appears. 

For example, we could record a short video that shows you how to archive a model and delete it based on the instructions we already have. 

### Placement

For end-to-end videos, they should live on a landing page as they typically cover several tasks. For example, for the videos in this PR, they cover tasks from several parts of our model validation docs:

image

### CODE REVIEW

**Comment by validbeck** [comment]
- The embed via playlist is definitely much better!
- I think the video embeds should go AFTER the title cards to the articles, with some sort of lead in text describing what you're going to be clicking on. 

I'm not sure if you want me to go over the videos now in the quality that they are, or wait until the "good" ones are out?

**Comment by nrichers** [comment]
> * The embed via playlist is definitely much better!

Agreed, I think that's the way forward for multi-part videos on the same topic. 

> I'm not sure if you want me to go over the videos now in the quality that they are ...

If you can provide feedback on the style & tone, that would be helpful. I need to move on to other videos this week but if these are good enough for now, I might leave them in until I can go back to re-record them.

**Comment by validbeck** [comment]
> If you can provide feedback on the style & tone, that would be helpful. I need to move on to other videos this week but if these are good enough for now, I might leave them in until I can go back to re-record them.

Overall the tone and cadence is very nice, thank you for working hard on these! The screencapture quality isn't the best like you mentioned but it's a little more readable on a screen smaller than your 8k one. 

## Global comment
We might want to make sure the descriptions of the final uploads have links to all the other videos in the playlist, and a quick summary of the video content.

### Introduction
- Maybe when you say the URL it should also be overlaid on the screen at the top (so as to not interfere with any CC etc) 
- You might want to mention that "Model Findings" is ALL model findings, rather than model-specific findings

### Reviewing 
- **For some reason the audio on this does not play for me at all.** 

### Analyzing test results
- I can hear the Slack notification a few times in this one 😅 ... perhaps mute notifs for the next round of recordings?

**Comment by nrichers** [comment]
I'm going to close this PR — I'm 4/5 done re-recording those videos with new intro slides and much better production quality. Will post a PR when I am able to record the final video.

**Pull request closed without merging**
