### PR TITLE
Rework training section & update validator training

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

They say you should leave the place better than you found it. I was in the process of updating our validator training but I decided that the structure of our training pages really needed some help. In this PR, I have:

- **Reworked the top-level training page** to be less about the details of the training environment and more about available courses. Use fewer words and put the important stuff first. 
- **Introduced course pages** with registration links. Registration is a bit makeshift for now but single-sourced between the courses. 
- **Renamed the training modules** to explain that they cover the fundamentals, in preparation for future courses that will provide intermediate and advanced modules. That terminology seems easier to understand over courses that have "101" in the title which requires an understanding of academic course numbering schemes. 
- **Added a template for course pages** to make future course additions simpler.

These reworked training pages should move the needle for our nascent training program.

## New top-level training page

**[LIVE PREVIEW](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6622/update-validator-training-with-tracking-issues/training/training.html)**

| Before | After |
|----------|----------|
| Capto_Capture 2024-10-24_06-12-18_PM | Capto_Capture 2024-10-24_05-32-09_PM |

### New course pages

| Administrator Fundamentals | Developer Fundamentals | Validator Fundamentals |
|----------|----------|----------|
| image | image | image |

## New section for validator training

I also addressed the story for expanding our validator training with **issue tracking & resolution**: 

- **Added a new "Track issue resolution" section** in the validator training with new slides, one with the steps and the other for trying it out: **[Direct link](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6622/update-validator-training-with-tracking-issues/training/validator-fundamentals.html#/track-issue-resolution)**
- **Single-sourced the new steps** for tracking open issue resolution with our user guide: 
   - **[Direct link - training](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6622/update-validator-training-with-tracking-issues/training/validator-fundamentals.html#/section-16)**
   - **[Direct link - user guide](https://docs-demo.vm.validmind.ai/pr_previews/nrichers/sc-6622/update-validator-training-with-tracking-issues/guide/model-validation/add-manage-model-findings.html#track-issue-resolution)**
- **Simplified some language & other minor tweaks**. Examples: 
   - Simplified "Select a model by clicking on it" > "Select a model" (redundant verbiage)
   - Moved "(Scroll down for the full instructions.)" directive into the column where the directive applies

### New "Track issue resolution" section

| Section | Steps |
|----------|----------|
| image | image |

| Try it out live | User guide |
|----------|----------|
| image | image |

## External Release Notes

We introduced a new training home page that makes it easier to find and register for our courses and expanded our validator training and user guide with more guidance for tracking and resolving the issues identified in model findings. [Training](https://docs.validmind.ai/training/training.html){.button}

### CODE REVIEW

**Review by validbeck — APPROVED** [review]
Ohhh, I love the structure of this new training section!! Nice work reorganizing everything into some more accessible modules.

---

Some comments on the stuff I added: 

- Is there a reason we're showing the publication date for the training tile cards? AFIAK, these don't update with edits, just the initial creation. I think we forgot to indicate we don't want it to display...? Anyhow, I removed them.
- I played around with using the role graphics on the training landing pages, since they are related to the info! Also used the same listing style on the index to reduce referencing the `.html` outputs. 

| Training | Index |
|---|---|
| Screenshot 2024-10-25 at 11 56 02 AM | Screenshot 2024-10-25 at 11 56 09 AM|

- JupyterHub is all one word, so I've adjusted that where it was spaced.
- The reworked "fundamentals" landing pages needed the redirects from the old training slides and used the listing tiles here as well:

| Administrators | Developers | Validators |
|---|---|---|
| Screenshot 2024-10-25 at 11 56 17 AM | Screenshot 2024-10-25 at 11 56 23 AM | Screenshot 2024-10-25 at 11 56 29 AM |

- I adjusted the severity criteria to include numbering, since it does in the UI:

| UI | New text |
|---|---|
| Screenshot 2024-10-25 at 11 54 49 AM| Screenshot 2024-10-25 at 11 54 46 AM|

- The "Register" single-source needed some TLC, some typos, and the `available courses` link no longer booting you up to the top div and the "provide feedback..." not linking you to the actual section since it can't pull the single-source header — fixed with span ids.
- The single-source files also didn't match our `-` file convention. The underscores should ideally only be at the front for the embed files.

**Comment by nrichers** [comment]
> * Is there a reason we're showing the publication date for the training tile cards? AFIAK, these don't update with edits, just the initial creation. I think we forgot to indicate we don't want it to display...? Anyhow, I removed them.

I'd simplified the listing YAML and removed which fields we pull in which in turn pulled on the date. I kinda liked the white space this introduced but the date doesn't add a whole lot, so removing makes sense to me. 

> I played around with using the role graphics on the training landing pages, since they are related to the info!

This feels like a _déjà vu_ of our home page discussion — I strongly prefer if we revert to the original graphics or the preview for the courses and will push a commit to that effect. These graphics have no connection to the courses themselves and just look b-u-s-y to me. We also removed these graphics from the home page role tiles for a similar reason — they don't add anything other than visual clutter.

This is not to say that we can't use some different graphics in the future. I quite like the iconography the neo4j uses for their courses, for example, see https://graphacademy.neo4j.com/categories/. This will be for a future PR, though, as I think we should start developing a slightly separate visual design for the training pages. I don't think I ever committed this experiment, but at some point I actually played around with icons from our main website to see if they could be used for the different courses. Definitely worth chatting about more in the future, though.

The rest of the changes are GREAT and I appreciate that you made these tweaks. 💖 Thank you so much!

**Comment by validbeck** [comment]
>  I strongly prefer if we revert to the original graphics or the preview for the courses and will push a commit to that effect. 

- I don't like that all of the images are the same. I think this doesn't add anything.
- I also don't like that we use the `.html` links in the `iframes` for the previews... again, complex code for no reason.

**Comment by nrichers** [comment]
> * I don't like that all of the images are the same. I think this doesn't add anything.

Let's chat at our community standup. I agree that having the same images be the same is also not great but it feels like a lesser evil. I did actually look into whether the tiles for listing pages could embed live content, but I'm not sure it's easy. Maybe there is some middle ground — e.g. I could even just use screenshots of the training title pages. 

> * I also don't like that we use the `.html` links in the `iframes` for the previews... again, complex code for no reason.

Related to the complexity introduced by the HTML code, agreed. I ran out of time on making improvements, but let me spend a bit of time this afternoon to create a new class for this.

**Comment by nrichers** [comment]
> > * I also don't like that we use the `.html` links in the `iframes` for the previews... again, complex code for no reason.
> 
> Related to the complexity introduced by the HTML code, agreed. I ran out of time on making improvements, but let me spend a bit of time this afternoon to create a new class for this.

I solved this issue. We now have a new extension via https://github.com/validmind/documentation/pull/488/commits/da2ed0e54ac8e9ec9a07c7ecc8b88d4156bdc2b8 that allows you to use `course-preview` with .qmd files, e.g. 

::: {.course-preview src="validator-fundamentals.qmd"}
:::

Style guide info coming shortly ...

**Comment by nrichers** [comment]
> > I strongly prefer if we revert to the original graphics or the preview for the courses and will push a commit to that effect.
> 
> * I don't like that all of the images are the same. I think this doesn't add anything.

If my extension for course previews was decidedly more clever, my solution for this issue is rather low tech: For now, I have added images of the title page for each course.

image 

There's very likely a better way to handle this but I'm out of time on this PR. In the future, we might look into a more bespoke listing tile we can create that also shows the live preview or automatically generate images from an URL.

**Comment by validbeck** [comment]
Nice!!

The only thing is, why is `Administrator Fundamentals` in two rows? Strange...

**Pull request merged**
