### PR TITLE
Updated Log In button to match main site + CSS updates to Training & Developer sections

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> sc-7648

### Updated buttons

[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7648/update-login-button-match-main-site/index.html)

- `Log In` now more or less matches the main website
- All buttons are now also less round, to match the main website's rounding

| Old | New |
|---|---|
| Screenshot 2024-12-06 at 10 38 14 AM| Screenshot 2024-12-06 at 10 38 26 AM|

### Global filters

Filters have been added globally, to `_quarto.yml`, so that we no longer have to go "wait, why are the flexboxes/previews/etc not working ohhh I forgot to apply it on this page...":

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/_quarto.yml#L433

They've been subsequently removed from anywhere they were applied on the page level.

#### `skip_preview`

Unfortunately applying the global `preview` filter had an oddity for the revealjs slides. It would add an extra empty slide:

skip-preview

To get around that, I added the ability to disable the `preview.lua` filter on a page level as necessary:

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/_extensions/nrichers/preview/preview.lua#L16

Then added it to the slide pages (and the template), and problem solved:

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/training/administrator-fundamentals/administrator-fundamentals.qmd#L23

### Global `.lightbox`

I've applied the same logic to this feature and added it to `_quarto.yml` as after some thought there are very few cases where we don't want the user to be able to enlarge images:

Screenshot 2024-12-06 at 12 06 08 PM

[Allegedly adding `.no-lightbox` on an image level if we don't want it to apply to a specific image is supposed to work](https://quarto.org/docs/output-formats/html-lightbox-figures.html#disabling-lightbox-for-specific-images), but when I tested this locally this isn't the case with a global or even page level flag, so I wonder if it's a Quarto bug...

https://github.com/validmind/documentation/blob/8fcf0d0760e6db732884a587a8586358dc2889b0/site/_quarto.yml#L432

**The only exception is that this still needs to be applied on the page level YAML for Revealjs slides (as adding it at the directory level `_metadata.yml` did not work nor did it respect the global setting), but it's already in our course slide template so not a big deal:**

Screenshot 2024-12-06 at 11 31 56 AM

#### Training

**[LIVE PREVIEW](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7648/update-login-button-match-main-site/training/training.html)**

I realised that we don't have to manually add `training.css` to each training page in the page-level YAML header. [Instead we can use a directory level metadata file to apply the stylesheet to the entire directory](https://quarto.org/docs/projects/quarto-projects.html#directory-metadata):

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/training/_metadata.yml#L4

##### Conflict with Revealjs

[Turns out that there is some expected but odd behaviour when there is a directory level metadata file](https://github.com/quarto-dev/quarto-cli/issues/10544). tl;dr, when you define a `format` in a metadata file, it then renders each file in the directory in that format, *even those that have a different output format designated*, like Revealjs:

> The one exception to metadata merging is format. If the document-level YAML defines a format, it must define the complete list of formats to be rendered.

Since Revealjs & HTML have the same output URL by default, this threw an error for our training slides as it tries to overwrite the file during both format outputs causing a conflict:

preview-extension

Not to worry, fix is easy and has been added to all slides (and the slide template):

- Under `format` AFTER `revealjs`, add:

```yaml
html:
# Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
  output-file: _course-slides.html
  search: false
```

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/training/training-templates/course-slides.qmd#L21

- This creates a `.html` output file with the alternate file name, with the search toggled to false so it doesn't show up on site searches but allows the page to render with Revealjs version & HTML version fulfilling the requirements for formats outlined by the directory-level `_metadata.yml`. 
     - [And now the course slides & subsequently the preview render as expected.](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7648/update-login-button-match-main-site/training/administrator-fundamentals/administrator-fundamentals-register.html)
     - If you do a site search for any of the course pages, you only get the Revealjs version returned.

##### New training drop-down top nav

I've hidden the regular top-nav for the training section and added instead two drop-down menus by the `Log In` menu:

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/_quarto.yml#L99

| Old | New |
|---|---|
|Screenshot 2024-12-06 at 10 57 16 AM | Screenshot 2024-12-06 at 10 56 47 AM|

#### Developer

**[LIVE PREVIEW](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7648/update-login-button-match-main-site/developer/get-started-validmind-library.html)**

This now also has it's own [`developer.css`](https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/developer/developer.css) & [`_metadata.yml` directory level metadata](https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/developer/_metadata.yml), featuring it's own distinct top-nav and new drop-down to signify content-shift to users:

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/_quarto.yml#L76

| Old | New |
|---|---|
| Screenshot 2024-12-06 at 10 59 28 AM | Screenshot 2024-12-06 at 10 59 17 AM|

I think this now looks much more like a "developer" portal without being its own project so hopefully you don't hate it. 🤞🏻 

##### Updated Makefile

But wait, you say, the `developer/` section includes the directories `notebooks/` and `tests/` which get overwritten every time we call `make get-source`!

I thought of that. Now the `notebooks` & `test-descriptions` commands wrap up by copying the `developer/_metadata.yml` file into their respective folders when we call `make get-source`:

https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/Makefile#L54
https://github.com/validmind/documentation/blob/c2860328a196ae3722874ebfd2d8374bdda5545a/site/Makefile#L78

| Notebook with `developer.css` | Test with `developer.css` |
|---|---|
| Screenshot 2024-12-06 at 11 05 29 AM| Screenshot 2024-12-06 at 11 05 39 AM|

### CODE REVIEW

**Review by nrichers — APPROVED** [review]
> Filters have been added globally to `_quarto.yml` …

Filters can conflict. For example, while testing Tachyons and Multimodal together, I noticed some wonky DOM issues. It's fine for now, but we might need to test new extensions we add to ensure they play nice with our existing ones.

> `output-file: _course-slides.html`

Not sure if this is related, but the preview now always renders three training courses for me?

### Some musings on our CSS  

We’re overloading `styles.css` with content that should go into `theme.scss` to enable a future dark mode. Also, we’ve added 700+ lines of CSS by now, which seems excessive for a docs site — and that’s just in `styles.css`.

We should consider what can be removed at some point, even if it leads to a simpler-looking site (not a bad thing, in my opinion). We’re reaching a level of visual tweaks that’s beginning to distract from the reading experience.

We're mixing assets under `/site/training/assets` (e.g., `training.css` and images) but follow a more disciplined approach under `/site/assets`. Training should align with the main site for consistency.

I also noticed that some hero banner assets are misplaced. For instance, our home page uses an asset that lives in `/site/training/assets`. Assets should reside in the appropriate folder.

In `b2a6cdadac07d9e5a8901f6533da1e11e356c646`, I made some changes:

- **White logo in the developer portal navbar** — The square pink logo on dark green doesn’t work for me. It feels instantly dated, and the fuchsia-esque pink against that shade of green is hard to read. I think we need to switch the login button and search icon to white as well. Additionally, the solid dark green bar looks stale as-is.  

- **White text on the training landing page hero banner** — The light green text on the training landing page hero banner didn’t work for me. It removed the feeling of crispness from the page.  

- **White background for the training course navbars** — The light green header on training pages looks like broken CSS to me. I can’t remember the compromise we agreed on, but I likely misunderstood your original intentions.  

The rest looks great — thank you for making these changes!  🚀🚀🚀

**Comment by validbeck** [comment]
> I also noticed that some hero banner assets are misplaced. For instance, our home page uses an asset that lives in /site/training/assets. Assets should reside in the appropriate folder.

These were just pulled from the folder they originally lived in — I think you used uploaded them to use in training and I stole them after, but you're right that we should shuffle some stuff around if they are used globally. I'll see if I have bandwidth for that in this PR but if I don't you might need to make a related Story.

**Comment by validbeck** [comment]
Went spelunking on our new website for some other tasty minimal graphics. You're going to have to preview locally as the ValidMind Library got a breaking change that needs to be merged before we can fix the workflows attached to execution: https://validmind.slack.com/archives/C04U7TKHH62/p1733877855321569

> Not sure if this is related, but the preview now always renders three training courses for me?

This doesn't happen to me, so not sure what's going on with your local settings? 🤔 

> White logo in the developer portal navbar — The square pink logo on dark green doesn’t work for me. It feels instantly dated, and the fuchsia-esque pink against that shade of green is hard to read. I think we need to switch the login button and search icon to white as well. Additionally, the solid dark green bar looks stale as-is.

Thanks for explaining this — after some thought I agree, so I went with a modern pink-slightly darker pink gradient (for some reason the logo has a different background colour than our standard brand pink and it stood out) with an angled cut-out that mimics the angle of a checkmark:

| Web | Mobile |
|---|---|
| Screenshot 2024-12-11 at 1 50 42 PM | Screenshot 2024-12-11 at 2 07 51 PM|

> White text on the training landing page hero banner — The light green text on the training landing page hero banner didn’t work for me. It removed the feeling of crispness from the page. White background for the training course navbars — The light green header on training pages looks like broken CSS to me. I can’t remember the compromise we agreed on, but I likely misunderstood your original intentions.

I revamped the training hero as well, with the bonus of the top-nav now having some cohesion without (hopefully) feeling intrusive:

| Web | Mobile |
|---|---|
| Screenshot 2024-12-11 at 2 08 16 PM| Screenshot 2024-12-11 at 2 08 54 PM |

Top nav: 

Screenshot 2024-12-11 at 2 08 30 PM

And finally, a revamped index page:

| Web | Mobile |
|---|---|
|Screenshot 2024-12-11 at 2 09 58 PM| Screenshot 2024-12-11 at 2 10 17 PM|

**Review by nrichers — APPROVED** [review]
# This looks great, Beck! 🎆 

Seriously, I love these latest changes. Thank you so much for listening to my concerns and turning those into something way better than I could have imagined.

One minor suggestion: **add a home page link** to the drop-down navigation menu for the developer and training portals. With the new drop-down menu, we're training our users to use the menu to navigate. However, the documentation home page is not in that menu, you can only get back via the VM logo on the top left.

image

**Comment by validbeck** [comment]
> One minor suggestion: add a home page link to the drop-down navigation menu for the developer and training portals. With the new drop-down menu, we're training our users to use the menu to navigate. However, the documentation home page is not in that menu, you can only get back via the VM logo on the top left.

I think this is even better:

| Developer | Training |
|---|---|
|Screenshot 2024-12-12 at 10 42 03 AM |Screenshot 2024-12-12 at 10 43 37 AM |

The button is hidden on mobile since the views already put the logo which takes you to the homepage at the top above the menus. Looks the same as before:

| Developer | Training |
|---|---|
| Screenshot 2024-12-11 at 2 07 51 PM| Screenshot 2024-12-11 at 2 08 54 PM|

**Comment by nrichers** [comment]
> I think this is even better

Yup, that works! We just needed something in or near the menu but the home page link is somewhat special. Putting it into an icon right next to the menu solves the issue.

**Pull request merged**
