### PR TITLE
Docs Site Audit - Scoping & Initial Styling

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> For sc-4459:
> - Set up [audit tracking in Notion](https://www.notion.so/validmind/2024-Docs-Site-Audit-Keywords-Initiative-7bfbe3e9dac94277b5c7e7bdcd123c9e?pvs=4)
> - Adjusted the styling of the callout blocks & removed ~15 extraneous callouts
> - Added `backtick` conventions to the Style Guide
> - Reviewed code blocks for declared language & adjusted the styling so that code blocks wrap
> - Made the `%pip install validmind` command uniform on the advice of John
> - Changed "Jupyter Hub" to `JupyterHub` as the official product is all one word
> - Adjusted the styling of links to be our ValidMind pink, with underline on hover
> - Adjusted the styling of our content tiles to a pink heading & border

callouts-style

- Cleaned up the callouts to minimize clutter
- Adjusted the styling of the remaining callouts to be visually coherent
- Quick adjustment to the `Key ValidMind Concepts` to indicate an expand menu

| Example | Old Callout Styling | New Callout Styling |
|---|---|---|
| Warning (`.callout-important`) | Screenshot 2024-06-11 at 12 24 15 PM| code-warning|
| Key concepts | Screenshot 2024-06-11 at 12 24 34 PM| new-key-concepts| 
| Note | Screenshot 2024-06-11 at 12 26 30 PM| Screenshot 2024-06-11 at 12 26 34 PM|

### Links & content cards
- To modernise the links and make the content tiles more similar to the links, I added some pink ValidMind™ styling. 
- Page body links will show underline on hover.

| Old | New |
|---|---|
| Screenshot 2024-06-11 at 12 19 49 PM | new-links-and-cards|

### Code content styling
| Old | New |
|---|---|
| Screenshot 2024-06-11 at 12 22 23 PM| code-content | 

I adjusted the style guide slightly to accommodate for our new code styling (with wrap / light grey BG that is a slightly different shade than our callouts) and cleaned up all the pages with code blocks:

| Old Code Blocks | New Code Blocks |
|---|---|
|Screenshot 2024-06-11 at 12 28 07 PM| code-wrap| 

### Backticks
backticks

I added a `backticks` section to the Style Guide, and made sure we followed this convention on our pages.

### JupyterHub
I manually replaced all the files I was able to access on my branch and checked them to make sure they updated. Below is an example from the "Welcome to the ValidMind sandbox!" page.

| Old | New |
|---|---|
| Screenshot 2024-06-11 at 12 18 47 PM | Screenshot 2024-06-11 at 12 16 18 PM |

### CODE REVIEW

**Review by noosheenv — COMMENTED** [review]
Beautiful changes! I love the look of the callouts. I'm not sure if I did this right, but all the suggested changes are for one idea: keeping the links black, and turning pink on hover. In addition, the cards' borders will turn pink on hover. Here is a gif to demonstrate:

Screen Recording 2024-06-11 at 12 59 14 PM

One more thing, I love the look of the "Key ValidMind Concepts" dropdown callout, but I would like the arrow to change state when it's clicked. For example, it looks like this ▶️  when collapsed, and looks like this 🔽  when expanded.

Everything is beautiful, thank you for doing such a thorough and complete audit!

**Comment by validbeck** [comment]
> Beautiful changes! I love the look of the callouts. I'm not sure if I did this right, but all the suggested changes are for one idea: keeping the links black, and turning pink on hover. In addition, the cards' borders will turn pink on hover. Here is a gif to demonstrate:

- Thank you for the suggestions! I don't love the links being underlined in solid black, as it's quite busy. The pop of pink gives some visual distinction and reduces clutter. I will play around with some more underlining options as there are some accessibility concerns there.
- I do like the hover for the CTA idea though, but I might swap the colour-schemes around.

> One more thing, I love the look of the "Key ValidMind Concepts" dropdown callout, but I would like the arrow to change state when it's clicked. For example, it looks like this ▶️ when collapsed, and looks like this 🔽 when expanded.

This isn't actually possible without some JavaScript as far as I'm aware due to the nature of the call-outs, but I will see what I can do.

**Comment by validbeck** [comment]
new-hover

- Added an underline to links, but kept them pink. They turn black on hover, with a pink underline.
- Added a hover to content tiles, but kept the titles pink. The content tile borders turn black like the links, but the text remains pink. 
- Switched out the collapse callouts back to `{.callout-important collapse="true" appearance="minimal"}` as this is the only way to get the collapse menu to change from expand/collapse automatically even though it's a weird hack.

**Review by nrichers — APPROVED** [review]
After playing around with this PR locally for a while my impression is **very positive**: this new look feels fresh and clean. :shipit:  

All my comments are minor. I say we publish this as soon as you feel this is ready to merge.

Some general comments about styling:

- Pink AND bold for links feels off almost all of the time — we should not use bolding in links, except maybe to highlight some very specific things (e.g. it looks OK for notebook titles in a table, but anything inline or in a callout feels too heavy handed). I know we have a few of these kicking around, including some that I am responsible for. If the old link style was too plain and sometimes required bolding, I’d say the new one feels sufficiently strong that it does not benefit from bolding 99% of the time. 
- Let’s be disciplined about minimising inline links, e.g. let’s not throw people off track with links to other docs in procedural steps or conceptual overviews. Much more visible links make this more important than before. The right answer should to put them into the links section at the bottom or to put things like glossary items into a newfangled flyout via Nutshell (the extension in my training PR). 
- Our style guide will need more updates as reveal.js styling and HTML styling don’t overlap 100% and our training content will have some of its own requirements. I’m going to defer that to a separate story as I need to merge the training PR soon, but let’s chat more.

Also — the gift that keeps on giving — the links on the front page don’t behave like the links in the rest of the docs which is much more noticeable now. 😛 

> Obviously, I wasn't able to review the inconsistencies in any of the training modules [@nrichers](https://github.com/nrichers) is working on. There are several instances of "Jupyter Hub" instead of JupyterHub for example.

I checked, there should be no misspellings of “JupyterHub”. Note the old "Welcome to the ValidMind sandbox!" topic is replaced by “Welcome to ValidMind Academy”. 

> EDIT2: I think I still like the no-underline for links better, as this is what is seen in the training modules Nik has been creating as well, but accessibility... Nik, what do you think?

I agree, no underline works better for me. Underline on hover looks good (could be black underline or pink, my preference would be for black underline on hover)

**Comment by validbeck** [comment]
> Pink AND bold for links feels off almost all of the time — we should not use bolding in links, except maybe to highlight some very specific things 

Noted, I will put this in an item in our next audit Story so I remember to catch any of these that are a bit much. 

> Let’s be disciplined about minimising inline links

Looking forward to your Nutshell improvement, otherwise I already have an item for minimizing additional inline links (other than the login, you must login!!) one in the next audit Story.

> Our style guide will need more updates as reveal.js styling and HTML styling don’t overlap 100% and our training content will have some of its own requirements. 

Happy to defer to you there, or if you just tell me what you want those guidelines to be to be I can help. 🎉 

> I checked, there should be no misspellings of “JupyterHub”. Note the old "Welcome to the ValidMind sandbox!" topic is replaced by “Welcome to ValidMind Academy”.

Noted, and when I reviewed your branch this morning it all looked fine to me in this regard.

> I agree, no underline works better for me. Underline on hover looks good (could be black underline or pink, my preference would be for black underline on hover)

I ended up going with the black hover, and some shading on the cards on hover as well:

hoverzzz

**Pull request merged**
