### PR TITLE
Add PR previews

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This PR adds automatic previews that 

- get deployed to our docs-demo site when you create or update a PR; AND 
- get deleted when the PR gets merged or closed

In our docs CI/CD deployment proposal, this PR adds the following highlight:

image

### Deploy PR preview 

Successful run: https://github.com/validmind/documentation/actions/runs/10673952942

image

image

image

### Delete PR preview

Successful run https://github.com/validmind/documentation/actions/runs/10674028315

image

image

## How it works

We already had a check to render the docs site and run tests. Together with a bit of editing of the existing workflow, we now basically take the output of that `quarto render` step and sync it to AWS S3, making it an efficient solution to deploy PR previews. 

**Why not a separate workflow to deploy PR previews?** The existing quarto render CI check gives us everything we need and is also the most expensive check to run, taking ~5 minutes to complete. 

The PR preview delete is just the `aws s3 rm` command performed on the same path in the docs-demo S3 bucket. The delete is silent as it's not something an author or reviewer needs to engage with — failures in the action should result in an email from GitHub. 

## How to test

- **Deploy PR preview**: Add a commit to this PR and watch it get deployed via the `Validate docs site (render, test, and deploy)` CI check. Use the preview URL from the comment to check the preview is there.
- **Delete PR preview**: Close this PR, wait for the `Delete PR preview` action to run, recheck the preview URL (it should 404), and then reopen this PR

### CODE REVIEW

**Comment by nrichers** [comment]
Test closing the PR to check if the PR preview gets deleted.

**Comment by nrichers** [comment]
Deleting worked, see https://github.com/validmind/documentation/actions/runs/10674028315/job/29583896617. 

Reopening PR.

**Comment by nrichers** [comment]
Test deleting PR preview by closing PR.

**Comment by nrichers** [comment]
Reopening PR for review & approval.

**Review by validbeck — APPROVED** [review]

**Pull request merged**
