### PR TITLE
Got rid of site unused

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> For sc-5565, I got rid of our `site-unused` folder.

#### WIP

| File tree | Description |
|---|---|
| Screenshot 2024-08-01 at 10 02 10 AM | Anything I didn't delete ended up in `site/wip` (`search` set to `false`). These were either upcoming product docs that had a nice skeleton or some conceptual docs we might want to revisit. |

@nrichers Let me know if you'd prefer to unthink-therefore-unam these bad boys and we can do that:

|  `conceptual` | `product` |
|---|---|
| `mermaid-diagrams-dev-framework.qmd` | `editions-and-features.qmd` (Refer to [Slack conversation here](https://validmind.slack.com/archives/C04FZR7DHMK/p1722530339531299).)|
| `mrm-lifecycle.qmd` | |
| `mrm-three-lines-of-defense.qmd` | |
| `mrm.qmd` | |

- It feels like the MRM ones are a bit covered in the glossary, but we should still think about expanding these "beginner" guides to make good on our claim of wanting to be an MRM authority, IMO. 
- Mermaid diagram one might be good to be moved into templates, just so we know how to structure diagrams in the future.

### Slight edits
- Updated the [`/faq/faq-privacy.qmd` page](https://github.com/validmind/documentation/pull/261/files#diff-7e7f367bc153b09d7372799330cbbc94bb814fa709853725d7f12eff632ef087) as there was one line from the duplicate file not present on this surfaced file
- There was a hidden merge conflict in a comment on [`release-notes.qmd` for `2024-may-22`](https://github.com/validmind/documentation/pull/261/files#diff-c79117336543623967f98cdfa47fa2eed65fe4c863090a1ce22e969421e1bd7a) so I resolved that
- I previewed the [`editions-and-features.qmd` file](https://github.com/validmind/documentation/pull/261/files#diff-f8efc17e0078be27328946cc459622a8294861797a6f12e1c3b52407b2af938e) and found that the `.column-screen-inset-right` didn't actually look too great so I removed it
- Updated the instructions on where to move stuff after you're done fiddling [on `/internal/testing.qmd`](https://github.com/validmind/documentation/pull/261/files#diff-a928498ab5da5fbdb0728e24d76672e48189423b4e395f7435cb17851e328257) (the `internal` folder OUTSIDE of `site` instead of into the now non-existing `site-unused`) 

### Comparisons

| | Old | New |
|---|---|---|
| File tree | Screenshot 2024-08-01 at 10 00 01 AM| Screenshot 2024-08-01 at 9 53 12 AM|
| README |Screenshot 2024-08-01 at 10 00 22 AM |Screenshot 2024-08-01 at 9 57 52 AM* |

*Just my VSCode preview theming, not to worry about the red.

### CODE REVIEW

**Review by noosheenv — APPROVED** [review]
I think this looks good, but we should wait for Nik to look just in case!

**Review by nrichers — CHANGES_REQUESTED** [review]
Can we agree that nothing should live in `site/` that isn't part of the public site? 

For this PR, I think this means moving `/site/wip` up a level or deleting. I know search is set to false for these files, but there's no reason to build and externalize them at all, as they are just old cruft. 

(I'd be fine with going one step further and just deleting that `wip` folder. All of the content in there is experimental from last year and largely defunct in its current form.)

**Comment by validbeck** [comment]
> For this PR, I think this means moving /site/wip up a level or deleting. I know search is set to false for these files, but there's no reason to build and externalize them at all, as they are just old cruft.

Fine by me! I just wasn't sure if you had any plans for the stuff in there that felt more fleshed out. I think I will keep the mermaid diagrams and put it into templates as a reference but otherwise I'm good with nixing the rest.

**Review by nrichers — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
