### PR TITLE
Add heap.io info to docs site headers

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This PR adds heap.io code to track how our docs are performing:

-  `_quarto.yml` — new `include-in-header` parameter that references `heap-production.html` 
- `heap-production.html` — the script include from heap.io for the `production` project
- `Makefile` — now prevents deploying the docs-demo site unless you are on the `docs-demo` branch with its own development project tracking

In the HTML output, these changes show up inside of `<head>` as expected:

image

More background info in [sc-5291](https://app.shortcut.com/validmind/story/5291/add-tracking-via-heap-to-our-docs-site).

### CODE REVIEW

**Comment by validbeck** [comment]
@nrichers Can I get access to heap.io so I can see some data? 😅

**Comment by nrichers** [comment]
> @nrichers Can I get access to heap.io so I can see some data? 😅

Right — that sort of would be required to make sense of this PR, wouldn't it? Invited you just now, check your email.

**Comment by nrichers** [comment]
@gtagle since you mentioned you're looking at Heap again — FYI, this PR will use the same project as our production Platform UI, based on convos I had with Mehdi & Andres, and what I found in the Heap documentation. 

Nothing you need to do, mainly just an FYI.

**Review by validbeck — APPROVED** [review]
I see the changes in `_quarto.yml` & `heap.html`, and see the script in the `<head>` on:

- Regular articles
- .`ipynb`
- Test descriptions

🎉

**Comment by nrichers** [comment]
@validbeck @noosheenv I've added some restrictions to our Makefile for deploying the docs-demo site: you now need to be on the docs-demo branch to deploy.

As discussed, the reason for this change is to avoid sending tracking info into our `production` project on heap.io that isn't actually production data (e.g., a PR in progress). 

The docs-demo site uses the `development` project for its own tracking.

**Pull request merged**
