### PR TITLE
Updated Edit model inventory fields

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> For sc-4756, I updated `edit-model-inventory-fields.qmd` so that the instructions match the actual UX.

### Edit model inventory fields

| Old | New |
|---|---|
| Screenshot 2024-07-02 at 4 22 02 PM | Screenshot 2024-07-02 at 4 21 50 PM |

### Changed files
**NB:** I tried to only include the edited files for review, but the merge from main changed a bunch of stuff... wargh.

### CODE REVIEW

**Review by nrichers — COMMENTED** [review]
LGTM! 🚢 

> NB: I tried to only include the edited files for review, but the merge from main changed a bunch of stuff... wargh.

This might be a case where rebasing rather than merging is preferable ... Related, pulling in `main` should be required less often once we have our new GitHub actions in place and can add the rendered output to the `.gitignore` file — fewer merge conflicts will mean less pulling.

**Comment by validbeck** [comment]
> This might be a case where rebasing rather than merging is preferable ... Related, pulling in main should be required less often once we have our new GitHub actions in place and can add the rendered output to the .gitignore file — fewer merge conflicts will mean less pulling.

@nrichers Can we perhaps book a session (maybe together with Noosheen?) so we can go over this? Would love to record that/take notes to see it in action as I'm not sure I fully understand the difference still 😓 

Also, for some reason it doesn't say you approved this PR...

**Review by nrichers — APPROVED** [review]
> Also, for some reason it doesn't say you approved this PR...

Fixed!

**Comment by nrichers** [comment]
> @nrichers Can we perhaps book a session (maybe together with Noosheen?) so we can go over this? Would love to record that/take notes to see it in action as I'm not sure I fully understand the difference still 😓

Yes, of course — it's about how you integrate or combine the different histories with `main`. This is a pretty good summary, especially the illustrations for how merge and rebase differ: https://www.atlassian.com/git/tutorials/merging-vs-rebasing.

**Pull request merged**
