### PR TITLE
Added a callout for workflow attachment options

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> sc-7292

Our workflows & inventory field docs are already pretty comprehensive, so I just added a brief callout to the `User Action` workflow step reference: [**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7292/documentation-support-attaching-files-on/guide/model-workflows/set-up-model-workflows.html#user-action)

Screenshot 2024-11-01 at 11 45 34 AM

### CODE REVIEW

**Comment by validbeck** [comment]
@cachafla Can you review and approve if it looks good? 🙏🏻

**Review by cachafla — APPROVED** [review]
Nice 👌

**Comment by validbeck** [comment]
@nrichers 

FTR, I added `.lightbox` to the style guide with this PR and applied it where appropriate:

Screenshot 2024-11-07 at 12 50 00 PM

- I also simplified `class="screenshot"` to `.screenshot` across the board as that was more effective. 
- Some neat stacked bubble styling with what was already added to style red/green text for x-marks and check-marks: 
https://github.com/validmind/documentation/blob/7b801289725478dd8dac34cf11788bd94748a209/site/styles.css#L470

Screenshot 2024-11-07 at 12 50 57 PM

**Comment by nrichers** [comment]
> @nrichers
> 
> FTR, I added `.lightbox` to the style guide with this PR and applied it where appropriate:

Thanks!

**Pull request merged**
