### PR TITLE
2024 aug 13 release fix on `prod`

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

I couldn't figure out why this release page is borked and still has the old buttons (both here and on the currently live site, and has been borked for a few publications): 

Screenshot 2024-11-04 at 5 22 55 PM

Screenshot 2024-11-04 at 5 35 50 PM

It looks fine on the local previews and in PR previews, so something is going on with the merging into `prod`. 🤔 The files look fine in `main` and `staging`:

- Main: https://github.com/validmind/documentation/blob/main/site/releases/2024-aug-13/release-notes.qmd
- Staging: https://github.com/validmind/documentation/blob/staging/site/releases/2024-aug-13/release-notes.qmd

When I pull in changes from `staging` into `prod` locally, the same information is retained even with `--strategy-option theirs`...

So what I ended up doing was creating this parallel PR to reset this file to `main` and hopefully that works going forward??

### CODE REVIEW

**Comment by validbeck** [comment]
@nrichers Forgot to tag you for visibility. Just FTR — not sure why stuff isn't being auto-merged from `main` into `staging` but I fixed it for this particular file.

**Comment by nrichers** [comment]
> @nrichers Forgot to tag you for visibility. Just FTR — not sure why stuff isn't being auto-merged from `main` into `staging` but I fixed it for this particular file.

Acknowledged — merge conflicts between `main` and `staging` are possible, I've had to fix one myself. The tell-tale sign is an auto-merge PR that sticks around.

**Comment by validbeck** [comment]
> Acknowledged — merge conflicts between main and staging are possible, I've had to fix one myself. The tell-tale sign is an auto-merge PR that sticks around.

It wasn't a merge conflict, that's what I'm saying. It just always preferred the `staging` version over `main` without flagging it as a conflict.

**Comment by nrichers** [comment]
> ple, pulling in from `staging` to `prod` WITHOUT `--strategy-option theirs` produced NO conflicts and retained the information from `prod`.

We discussed and this sounds like GitHub simply got the merge wrong. It can happen and there are ways to mitigate the effect by 

- simplifying our branch strategy 
- stepping up our automated testing

or a combination of both. For now, let's watch how often this happens and decide if we need to step up our game.

**Pull request merged**
