### PR TITLE
Fix Heap embeds for docs sites — `staging` branch

### PR DESCRIPTION
**Pull request by nrichers**
## Internal Notes for Reviewers

This PR follows #339 and enables tracking for Heap in `staging` using the correct development project in Heap.

### CODE REVIEW

**Review by validbeck — COMMENTED** [review]
How do we ensure that this isn't overwritten automatically when `main` is merged into `staging`?

**Comment by nrichers** [comment]
> How do we ensure that this isn't overwritten automatically when `main` is merged into `staging`?

For the three PRs that I have on the go, you want to merge them in the right sequence: `main`, then `staging`, and then  `prod`. 

After that, the only way this would get overwritten is if someone deliberately re-adds Heap tracking to `_quartyo.yml` on `main`.

**Comment by validbeck** [comment]
> After that, the only way this would get overwritten is if someone deliberately re-adds Heap tracking to _quarto.yml on main.

I guess my confusion is won't what's in `staging` override what's on `prod`? 🤔 I think my hamster brain hasn't made the connections yet.

**Comment by nrichers** [comment]
> I guess my confusion is won't what's in `staging` override what's on `prod`? 🤔 I think my hamster brain hasn't made the connections yet.

Files differing between branches is not a concern, they should be transparent to GitHub unless there is an actual commit that needs to be merged from one branch into another.

**Comment by validbeck** [comment]
> Files differing between branches is not a concern, they should be transparent to GitHub unless there is an actual commit that needs to be merged from one branch into another.

That's what I mean, when we merge from `staging` into `prod` doesn't that unify them?

**Pull request merged**
