### PR TITLE
New homepage draft

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> sc-6237

### Done

- [x] Updated blurbs & hero banner
- [x] Getting started for admins
- [x] Better access for developer content (reference link)
- [x] What's new / latest releases
- [x] Training

[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-6237/shortlist-items-for-the-home-page/index.html)

### Discuss

- [ ] "Ask a question" chatbot — Happy to replace the search bar with this once we have a bot.
- [ ] Carousel of product screenshots — I don't personally think these are necessary, with what we have on the page right now. Less fluff, more info for docs. People can always go to the website for "marketing" content.
- [ ] Product tour video — Happy to make a section for videos once we have more.
- [ ] Cool code stuff — Again, I think we should keep the "fluff" to a minimum unless it demonstrates something really cool.

### CODE REVIEW

**Comment by nrichers** [comment]
Nice! I have some initial comments, mainly to simplify and group like things together, happy to chat more:

image

## Comments 
❶ — These three tiles with content for each role are GREAT! 💖 They take the idea of listing pages and take them to the next level. NICE! ✨✨✨ 
❷ — Please fix vertical alignment to be the same as the other boxes; some stylized code would be useful for the developer artwork here
❸ — This background is making me uneasy (feels like: 'screenshot with stray lines'?) 😱 
❹ — I would recommend subdividing this box as it contains too much related-but-separate stuff; I'd separate out training from support/FAQ (maybe use two containers with a 1/3 and 2/3 split across?); and move the CTA for requesting a demo into the "BeValid" section
❺ — For the sake of simplicity, I would prefer we limit to ONE blurb about the product in the page; I would use this section only for the demo CTA which could include some extra text
❻❼ — These old graphics don't add anything, IMHO, I'd opt for just the listing page tiles and remove the rest; on the fence about the data privacy policy, it feels like that belongs more into the footer
❽ —  The blog and open source belong into the community tile, and "ValidThoughts" is not the name for the blog, it refers to our webinar series; overall, I would limit the purpose of this section to be about releases and info contained in this site (again, use the the community tile for the rest)

**Comment by validbeck** [comment]
> Please fix vertical alignment to be the same as the other boxes; some stylized code would be useful for the developer artwork here

I originally had it all aligned the same, but I didn't like it as much. I personally like having the contrast of the indent for the second box, and it matches some of the indenting design we have on the main website but feel free to play around.

> This background is making me uneasy (feels like: 'screenshot with stray lines'?) 

This is the three checkmarks graphic from the main website as well, I played around with some different orientations but this looked best. Feel free to adjust yourself. 

I think I am personally done hacking at the homepage as I spent a lot of time late last night looking at it and this is the limit of my "design thoughts". My recommendation is that if you want the changes, BE (or make) the changes — I think that's more effective than us trying to convey what we're visualising back and forth in text. :)

**Comment by nrichers** [comment]
@validbeck:

1. This PR is AMAZING, I have started using this as the basis for my own mockups for what else we want (e.g. product tour video, chatbot).
2. I'd like a chance to edit/tweak this before we merge, so I added the `DO NOT MERGE` label for now.

Related to 2., I would propose that we reduce some of the font playfulness and simplify the visuals a bit, and remove the FAQ. The ask for Sprint 59 was only to enumerate what we want on the page, not implement it, meaning there is no requirement to merge this before EOD tomorrow.

**Comment by validbeck** [comment]
> Related to 2., I would propose that we reduce some of the font playfulness and simplify the visuals a bit, add a current screenshot, and remove the FAQ. The ask for Sprint 59 was only to enumerate what we want on the page, not implement it, meaning there is no requirement to merge this before EOD tomorrow.

I think you will need to tweak the font yourself, but I simplified the training section:

Screenshot 2024-09-25 at 3 57 35 PM

**Comment by nrichers** [comment]
@validbeck https://github.com/validmind/documentation/pull/441/commits/dd21b02435cb74bc183a6e0368d5f4a0cf96b9d2 is 

 

🔥🔥🔥

**Comment by validbeck** [comment]
Thanks @nrichers! Yes, I hadn't quite finalised the graphic there so if you wanted to play around with it a bit more that would be great. The only thing is the graphics are different heights, so when it animates without a set "div" around them all it changes the height of the hero section. 💀

**Comment by nrichers** [comment]
> [Simplified hero even though I don't like it](https://github.com/validmind/documentation/pull/441/commits/4607937c8a4a86bd4f75807aabb93ebc915fe7a7)

😂 FYI, I'm done tweaking the look in my version of your PR now and reimplemented the search on the front page to use the existing local search index before adding the first bits to enable AI chatbot stuff.

**Pull request closed without merging**
