### PR TITLE
New sidebar & ToC theme

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

From https://github.com/validmind/documentation/pull/521

> Looking at preview, I think we'd need to apply this to both the sidebar navigation and right-hand ToC (or neither) for a consistent feel.

[**LIVE PREVIEW**](https://docs-demo.vm.validmind.ai/pr_previews/beck/sidebar-fiddling/index.html)

| Old | New |
|---|---|
| Screenshot 2024-11-13 at 10 59 03 AM| Screenshot 2024-11-13 at 10 58 45 AM|

### CODE REVIEW

**Comment by nrichers** [comment]
If you do want to do a solid background for the sidebar, I'd recommend something subtler that is closer to what the product does: 

image

It's quite subtle. With a solid background, maybe NOT doing the same on the left and the right would be preferable, as the preview feels a bit busy to me. (With JUST a text colour change, I'd try the same on both sides.)

**Comment by nrichers** [comment]
BTW, this is an example of a simple but interesting box treatment: https://graphacademy.neo4j.com/courses/gds-product-introduction/

All the same, I'd use a box or solid background on only one side.

**Comment by validbeck** [comment]
Why do you hate colour so much, Nik?? 😭 😭 😭 

I stole some other greens and some hover states from the platform, and I'm willing to live with this if you are:

Screenshot 2024-11-13 at 3 41 06 PM

Adjusted the drop-down as well since the hover state for the sidebar doesn't play nicely with BG shifts:

Screenshot 2024-11-13 at 3 44 00 PM

Simplified training to one `.css` sheet (and updated the conventions to match):

| Landing | Registration Pages |
|---|---|
| Screenshot 2024-11-13 at 3 44 32 PM | Screenshot 2024-11-13 at 3 41 37 PM |

**Review by nrichers — APPROVED** [review]
Nik apologizes to Beck for annoying them and expresses his gratitude and thanks for this PR. :shipit:

**Pull request merged**
