### PR TITLE
Updated docs for validation guideline settings

### PR DESCRIPTION
**Pull request by validbeck**
## Internal Notes for Reviewers

> For sc-5874 I:
> - Revamped `preparing-validation-reports.qmd`
> - Changed `view-validation-guidelines.qmd` to `manage-validation-guidelines.qmd` & moved it to the top-level of **Model Validation**
> - Updated `customize-documentation-templates.qmd` to reflect the new ongoing monitoring feature and added details for expanding/adding content (guidelines) to sections
> - Removed `Risk areas` from `set-up-your-organization.qmd` & retooled the single-sourcing for this page

### Preparing validation reports
- Cleaned up the intro
- Added requirement for validation guideline configuration to prerequisites
- Retooled the `Get started` section into more accurate instructions on how to interact with validation reports, including information on viewing validation guidelines (I decided this did not need to be its own page or even section, as they are pretty well integrated into the report building process)
- Made sure the `What's next` included all the other pages under this landing

| Old | New |
|---|---|
| Screenshot 2024-08-16 at 2 04 45 PM | Screenshot 2024-08-16 at 2 05 05 PM |
| Screenshot 2024-08-16 at 2 06 29 PM | Screenshot 2024-08-16 at 2 07 29 PM|

### View validation guidelines > Manage validation guidelines
- I retooled the old view validation guidelines page to a net-new page covering how to set up and attach guidelines to validation report templates (the old instructions were incorrect anyhow, as the UI has been updated)
- I moved this page to the top-level `model-validation` section and placed it **above** preparing reports as guidelines should ideally be set before reports are made

| Old | New |
|---|---|
|Screenshot 2024-08-16 at 2 11 10 PM | Screenshot 2024-08-16 at 2 11 58 PM |
| ... | Screenshot 2024-08-16 at 4 07 54 PM |
| ... | Screenshot 2024-08-16 at 4 08 05 PM |
| ... | Screenshot 2024-08-16 at 2 12 46 PM |

### Customize documentation templates
- Adjusted the `Edit template outline` section to include information on how to expand sections & add content to validation report templates
- Tweaked the wording to include ongoing monitoring templates, more generalized references to templates etc.

| Old | New |
|---|---|
| Screenshot 2024-08-16 at 2 15 08 PM | Screenshot 2024-08-16 at 2 15 20 PM |

### Set up your organization
- Moved the `Risk areas` section to the bottom and linked out to `manage-validation-guidelines.qmd` instead
- I tweaked or cleaned up the other `set-up-your-organization.qmd` single-sourcing files as well to match this format and made sure they look OK in the training as well

| Old | New |
|---|---|
| Screenshot 2024-08-16 at 4 09 28 PM |Screenshot 2024-08-16 at 4 11 51 PM |
| Screenshot 2024-08-16 at 4 09 38 PM| Screenshot 2024-08-16 at 4 12 15 PM|
| Screenshot 2024-08-16 at 2 43 13 PM | Screenshot 2024-08-16 at 2 43 30 PM |
| Screenshot 2024-08-16 at 4 10 42 PM | Screenshot 2024-08-16 at 4 13 11 PM |
| Screenshot 2024-08-16 at 4 10 51 PM | Screenshot 2024-08-16 at 4 13 17 PM|
| Screenshot 2024-08-16 at 4 10 47 PM | Screenshot 2024-08-16 at 4 13 22 PM|

#### Listings & What's next
- Adjusted the look of some of the listings (layout, content) to better reflect the standard established by more recent articles
- Edited/adapted the `What's next` section of some articles to be more relevant or comprehensive

**Examples:**

| Old | New |
|---|---|
| Screenshot 2024-08-16 at 2 16 17 PM | Screenshot 2024-08-16 at 2 16 21 PM |
|Screenshot 2024-08-16 at 2 17 54 PM | Screenshot 2024-08-16 at 2 18 00 PM|

#### Unified display of `+` & `x`
- For consistency, I changed all `+` signs or `circle-plus` icons to the `plus` icon where appropriate (making sure it matched what was in the UI).
- I also changed any `x` to the FA `x` icon instead

**Example:**

| Old | New |
|---|---|
| Screenshot 2024-08-16 at 2 26 19 PM | Screenshot 2024-08-16 at 2 26 30 PM|

### CODE REVIEW

**Comment by validbeck** [comment]
Nik: Oops, don't know how I removed the review. Sorry for the double-notif. 🫠

**Review by nrichers — CHANGES_REQUESTED** [review]
Will approve after you make the requested changes. 

**Why I marked this as `Request changes`**:

- Numbered steps without a clear task heading feels like saying 'here, do these steps' without also telling you what the steps do.  I’d ask that we avoid or discuss why we should allow this approach in our docs.

- Let's agree not to explain how the UI works, something `click X to cancel` does not belong. The suggestions I included to delete the text also required reworking some of the surrounding text, but please check I got them right. 

**Other comments:**

- References to things you perform actions on should be in the plural in headings, e.g. `#### Add guidelines` with an "s" at the end, similar to what you already had for risk areas. 

- The `After you confirm ...` additions that show up in the training modules feel especially useful, thank you! It's a small change but it works really well, IMHO.

**Comment by validbeck** [comment]
It was too confusing for me to look at the commit suggestions when pulled down without seeing the full context so I'm just going to redo them manually; sorry!

**Comment by validbeck** [comment]
Applied the suggestions manually, as I discovered my brain doesn't like the piecemeal commits (can't see them in context of the larger doc, especially when we're working out of single-sourcing files) & if I don't make the change myself I can't seem to understand what happened 😓 

I think I applied all the suggestions:

- Describe the action instead of the behaviour (not sure why I had trouble with parsing this, clearly I knew how to fix it...)
- Changed headers to the action you should perform as I retooled the structure of the content

Screenshot 2024-08-21 at 9 07 19 AM
Screenshot 2024-08-21 at 9 07 39 AM
Screenshot 2024-08-21 at 9 07 51 AM
Screenshot 2024-08-21 at 9 08 09 AM
Screenshot 2024-08-21 at 9 08 27 AM

**Review by nrichers — APPROVED** [review]
LGTM! Reviewed the changes based on your latest screenshots and then also spot tested one of the tasks ("Add guidelines to template") — worked perfectly. 🚀🚀🚀

**Pull request merged**
